# Generated by Django 2.0.2 on 2020-06-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
