# Generated by Django 2.0.2 on 2020-06-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200628_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(unique=True, verbose_name='手机号'),
        ),
    ]
